### ISSUE TITLE
Documenting Resources with Sphinx integration

### ISSUE THREAD

**Issue by bomb-on** [mozilla-services/cornice#279]
I have a Pyramid+Cornice application and I'm using `resources` rather than `services`. I wonder if it is possible to generate Sphinx documentation for resources in a same way like with services?

I managed to generate some sort of documentation but it seems like majority of features are not available for resources, for example, documenting Pyramid code in this way:

    @resource(collection_path='/parse/', path='/parse/{id}', cors_origins=('*',), description="Temporary description.")
    class Parser(object):
    
        @view(renderer='json')
        def collection_post(self):
            """
            Some description for this function...
            :param str smth: Some parameter
            :return: Returns something
            """
            return

and building Sphinx documentation like this:

    .. cornice-autodoc::
       :modules: my_app.views.views_parser
       :ignore: parser

will result in few unnecessary and few missing parts in documentation:

 - service names (actually resource names) are messed up,
 - function `collection_post` itself is not documented,
 - no need to document both `collection_path` and `path` from `resource` declaration):

________________
<sub><sup>(example snippet from generated documentation)</sup></sub>
# Collection_Parser service at /parse/
Temporary description.

## POST
**Response: json**

# Parser service at /parse/{id}
Temporary description.

________________
What I would like to know is:  

 - how to change names generated in documentation (`Parser` instead of `Collection_Parser`),
 - how to 'ignore' some modules with `:ignore:` statement (e.g. I don't want to document `/parse/{id}` part),
 - how to document functions within Resources, since putting a comment block is just being ignored (`collection_post` in my case)

...and many other things...  
It seems like this is either impossible or not documented at all.  
Thanks for any help, tip or advice!

**Comment by ametaireau** [comment]
Hi!

Currently, we don't support that in a very helpful way. Collections have a few concepts in addition to what services expose, and cornice documentation generation is built around services.

As such, I believe you would be missing a bunch of information. We're currently thinking about doing a big refactor of how resources are defined and internally managed, and I believe documentation generation should be part of that thinking and change.

I suppose, on the short term, that the solution for you is to update the documentation generator to use resources rather than services.

Also, it's worth noting that we're considering a change in the way we're currently generating the documentation: rather than doing it programmatically (which is a pain), using templates could help.

Would you be willing to do anything related to this?

**Comment by bomb-on** [comment]
Hi Alexis and thank you very much for detailed answer.

When you said *"I suppose, on the short term, that the solution for you is to update the documentation generator to use resources rather than services."* does this mean that you are suggesting creating some sort of "dummy" services just as holders for automated documentation generation and nothing else?

About the templates... Well, I agree that it could be much easier to manage your documentation, but I'm afraid that at this moment I won't have much time to put my hands on it (although I would love to). Maybe sometimes in the future I can take a look at possibilities regarding this. If so, will definitely let you know about my ideas!

Thank you one more time for helping regarding this!

**Comment by ametaireau** [comment]
When using resources, cornice uses services behind the scenes and the documentation generator is built atop these services, it means that you lose some kind of information in the process (what's specific to your resource) but since we don't support resources in the documentation generation process, I believe the best way forward for you is to use this granurality.

**Comment by bomb-on** [comment]
Thank you for clarifying this. Will close this "issue" then :)
