### ISSUE TITLE
Registering Exception Views Through Cornice

### ISSUE THREAD

**Issue by vcatalano** [mozilla-services/cornice#336]
Currently, Pyramid has a way to register exception views (http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/pylons/exceptions.html#exception-views). The main drawback to using Pyramid's exception views is that you have to create a new Response object for each view. It would be nice if Cornice could provide a way to register exception views that pass in the existing response object so a new one doesn't have to be created. Something like this would be nice:

```python
@view_config(context=InvalidCreditCardError)
def bad_card(exc, request, response):
    response.errors.add('billing', 'formError', 'You entered an invalid credit card')
    response.errors.status = 501
    return response
```

Notice how the existing response object is passed into the function and errors and status can be easily set without creating a new Response object.

**Comment by ametaireau** [comment]
Hi, thanks for taking the time to open an issue here.

The problem I see is that because responses aren't global, and aren't attached to the current exception, I don't see any way to get back the current response when an exception is raised.

Maybe this would be possible with the stack trace, but I haven't experienced, and it seems like a bad idea, and I would rather re-create a new response rather than doing stack inspection like that (because it always adds complexity).

I'm going to close the issue for now. Feel free to re-open if you think my opinion doesn't make sense or if you have an alternative proposal.
